openapi: 3.1.0
info:
  title: サンプル
  version: v1
  description: |
    # タイトル1

    ## タイトル2

    * サンプル
      * `1001` 項目1
      * `1002` 項目2

    ## 表

    |カラム1|カラム2|
    | --- | --- |
    | 内容1 | 内容2 |


